project:
  type: website

website:
  title: "CAAD Futures 2025"
  favicon: "Stamp_CAADFutures2025_OUTLN.png"
  # back-to-top-navigation: true
  page-footer: 
    background: black
    left: 
      <div>Â© 2024, Hong Kong University, All rights reserved.</div>
    center: |
      <div>
      <img src="foabanner_inverted.png" alt="faculty of arch" style="height: 30px; margin-right: 10px; margin-top: 10px">
      </div>
    right: |
      <div>
      <img src="caadfutures.png" alt="caadfutures" style="height: 30px; margin-right: 10px;">
      </div>
      
    
  navbar:
    logo: "Stamp_CAADFutures2025_OUTLN.png"
    right:
      - text: "Home"
        href: index.qmd
      - text: "Calls"
        # href: call.qmd
        menu:
          - text: "Call for Regular Papers"
            href: regular.qmd
          - text: "Call for Proposals"
            href: props.qmd
      - text: "Committee"
        href: team.qmd
      - text: "Ambition"
        href: ambition.qmd
      # - text: "Conference Theme"
      #   href: conference_theme.qmd


format:
  html:
    page-layout: full
    theme: lux
    css: styles.css
    toc: true



